# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Janet Matsen's protocols
tagline:             'for metabolic engineering.'
description:         'Developed in the <a href="http://depts.washington.edu/mllab/" target="_blank">Lidstrom Lab</a>.'
url:                 http://janetmatsen.github.io/protocols
baseurl:             /

# About/contact
author:
  name:              Janet Matsen
  url:               https://twitter.com/janetmatsen
  email:             jmatsen@uw.edu

# Custom vars
version:             1.0.0
